version: '3'

services: 

  app:
    container_name: app
    restart: "always"
    image: golang:1.16.3 
    networks: 
      - app-db-network
      - web-app-network
    volumes: 
      - ./go/fullcycleservice:/go/src/fullcycleservice
    command: sh -c 'cd /go/src/fullcycleservice && go run main.go'
    tty: true
    depends_on: 
       - db

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    tty: true
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint.initdb.d
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycledb
    networks: 
      - app-db-network
    ports: 
      - "3306:3306"

  web:
    container_name: web
    restart: "always"
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - web-app-network
    ports:
      - "8000:80"
    depends_on: 
      - app
    

networks: 
  app-db-network:
    driver: bridge      
  web-app-network:
    driver: bridge      